cluster.name: travis
node.name: travis-node
node.max_local_storage_nodes: 1
index.number_of_shards: 1
index.number_of_replicas: 0
index.mapper.dynamic: true
action.auto_create_index: true
action.disable_delete_all_indices: true
path.conf: __HOME__/elasticsearch
path.data: __HOME__/elasticsearch/data
path.logs: __HOME__/elasticsearch/logs
bootstrap.mlockall: true
http.port: 9200
gateway.expected_nodes: 1
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.multicast.enabled: false
cloud.node.auto_attributes: true
marvel.agent.enabled: false
script.index: on
script.inline: on
