name: 'DigitalGov Search'
description: 'The core application powering the DigitalGov Search service, formerly USASearch'
license: null
openSourceProject: 0
governmentWideReuseProject: 0
tags:
    - GSA
    - DigitalGovSearch
    - search
    - SaaS
contact:
    email: search@support.digitalgov.gov
