name: 'Search.gov'
description: 'The core application powering the Search.gov service, formerly DigitalGov Search'
license: null
openSourceProject: 0
governmentWideReuseProject: 0
tags:
    - GSA
    - Search.gov
    - search
    - SaaS
contact:
    email: search@support.digitalgov.gov
