common: &default_settings
  api_key: ***REMOVED***
  ignore:
    - "ActionController::MethodNotAllowed"
    - "ActionController::UnknownHttpMethod"
    - "REXML::ParseException"
    - "EOFError"
  secure: false
  enabled: false

development:
  <<: *default_settings

test:
  <<: *default_settings

production:
  <<: *default_settings
  enabled: true
