common: &default_settings
  image_bucket:
    access_key_id: ***REMOVED***
    secret_access_key: ***REMOVED***
    bucket: ***REMOVED***
    s3_host_alias: ***REMOVED***.s3.amazonaws.com
    s3_region: 'us-east-1'

development:
  <<: *default_settings

test:
  <<: *default_settings

production:
  <<: *default_settings
