development:
  adapter: mysql
  database: usasearch_development
  username: root
  encoding: utf8

test: &TEST
  adapter: mysql
  database: usasearch_test
  username: root
  encoding: utf8

production: &PROD
  adapter: mysql
  database: usasearch_production
  username: root
  password: usa.gov
  encoding: utf8
  pool: 5
  timeout: 5000
  reconnect: true

production_slave_database:
  <<: *PROD

cucumber:
  <<: *TEST