development:
  adapter: mysql
  database: usasearch_development
  username: root
  encoding: utf8

test: &TEST
  adapter: mysql
  database: usasearch_test
  username: root
  encoding: utf8

production:
  adapter: mysql
  database: usasearch_production
  username: root
  password: usa.gov
  encoding: utf8
  pool: 5
  timeout: 5000

production_database_slave:
  adapter: mysql
  database: usasearch_production
  username: root
  password: usa.gov
  encoding: utf8
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST