development:
  host: http://localhost:8081
  admin_user: dev
  admin_password: devpwd

test:
  host: http://localhost:8081
  admin_user: test
  admin_password: testpwd

production:
  host: https://i14ydemo.usa.gov
  admin_user: usasearch
  admin_password: ***REMOVED***