production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    solr_home: #{RAILS_ROOT}/solr
    max_memory: 512M

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    solr_home: #{RAILS_ROOT}/solr

cucumber:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    solr_home: #{RAILS_ROOT}/solr

labs:
  solr:
    hostname: localhost
    port: 8992
    log_level: INFO
    solr_home: #{RAILS_ROOT}/solr
