consumer: &CONSUMER
  consumer_key: '***REMOVED***'
  consumer_secret: '***REMOVED***'

# TweetStream default configuration using usasearchdev account
default:
  <<: *CONSUMER
  oauth_token: '***REMOVED***'
  oauth_token_secret: '***REMOVED***'

# TweetStream configuration for cron using usasearch account
cron:
  <<: *CONSUMER
  oauth_token: '***REMOVED***'
  oauth_token_secret: '***REMOVED***'