:default: &DEFAULT
  :easy_options:
    :timeout: 15
    :headers:
      :user-agent: Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))

  :multi_options:
    :max_connects: 8

:throttled:
  <<: *DEFAULT
  :multi_options:
    :max_connects: 3
