---
http_interactions:
- request:
    method: post
    uri: https://api.flickr.com/services/rest/
    body:
      encoding: US-ASCII
      string: url=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fwhitehouse%2F&method=flickr.urls.lookupUser&format=json&nojsoncallback=1
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - FlickRaw/0.9.9
      Authorization:
      - OAuth realm="https://api.flickr.com/services/rest/", oauth_consumer_key="***REMOVED***",
        oauth_nonce="x1guCJqsDI9vpE7b8o5nqhBRWeukasGTbVpoXcAQBDo%3D", oauth_signature="***REMOVED***%26",
        oauth_signature_method="PLAINTEXT", oauth_timestamp="1484067712", oauth_token="",
        oauth_version="1.0"
      Content-Type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jan 2017 17:01:52 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '94'
      P3p:
      - policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM
        DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND
        PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      X-Content-Type-Options:
      - nosniff
      Cache-Control:
      - private
      X-Served-By:
      - www-bm011.flickr.bf1.yahoo.com
      X-Frame-Options:
      - SAMEORIGIN
      Vary:
      - Accept-Encoding
      Age:
      - '0'
      Via:
      - http/1.1 fts107.flickr.bf1.yahoo.com (ApacheTrafficServer [cMsSf ]), http/1.1
        r29.ycpi.gq1.yahoo.net (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"user":{"id":"35591378@N03","username":{"_content":"The White House"}},"stat":"ok"}'
    http_version: 
  recorded_at: Tue, 10 Jan 2017 17:01:52 GMT
recorded_with: VCR 3.0.3
